### Create

POST http://localhost:8080/api/accidents
Content-Type: application/json
Accept: application/json
Authorization: 26d72d89-e5ca-4db1-a1b8-7700dbb0a43f

{
  "date": "2023-06-17",
  "location": "Way Kanan",
  "description": "Kecelakkan terjadi di kabupaten Way Kn",
  "fatalities": 3,
  "injured": 2,
  "vehicle_type": "motor"
}

### Get All

GET http://localhost:8080/api/accidents
Content-Type: application/json
Accept: application/json
Authorization: 26d72d89-e5ca-4db1-a1b8-7700dbb0a43f

### Get One

GET http://localhost:8080/api/accidents/3
Content-Type: application/json
Accept: application/json
Authorization: 6276e104-929c-45be-a2b3-d18dc26e9bf1

### Update

PUT http://localhost:8080/api/accidents/3
Content-Type: application/json
Accept: application/json
Authorization: 6276e104-929c-45be-a2b3-d18dc26e9bf1

{
  "date": "2023-06-18",
  "location": "Way Kanan",
  "description": "Kecelakkan terjadi di kabupaten Way Kn",
  "fatalities": 6,
  "injured": 2,
  "vehicle_type": "motor"
}

### Delete Contact

DELETE http://localhost:8080/api/accidents/4
Content-Type: application/json
Accept: application/json
Authorization: 6276e104-929c-45be-a2b3-d18dc26e9bf1
